name: env_pescaz
channels:
  - conda-forge
  - bioconda
  - defaults
  - R
dependencies:
  - R>=4.1
  - r-tidyverse=1.3.2
  - r-plotly=4.10.1
  - r-markdown=1.4
  - snakemake=7.19.1
  - graphviz=7.0.5
  - coreutils=9.1
  - r-dbi=1.1.3
  - r-tidymodels=1.0.0
  - r-modeltime=1.2.4
  - r-timetk=2.8.2
  - r-lubridate=1.9.0
  - r-proc=1.18.0
  - r-rocr=1.0_11
  - r-aod=1.3.2
  - r-stringr=1.5.0
  - r-readxl=1.4.1
  - r-sjplot=2.8.12
  - r-vim=6.2.2
  - r-fsa=0.9.3
  - r-varhandle=2.0.5
 